routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', function () {return view('welcome');});

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function(){
    
    Route::get('file/view/{file}', 'FileUploadController@serveFile')->name('serve-file');
    Route::get('file/download/{file}', 'FileUploadController@downloadFile')->name('download-file');
    Route::resource('uploads', 'FileUploadController');

    // Route::resource('clients.documents', 'ClientDocumentController')->shallow();
    Route::get('/test','ClientDocumentController@getType');
    Route::resource('clients.documents', 'ClientDocumentController')->scoped();

    Route::get('datatable/{clientId}', 'ClientController@datatables')->name('clients.datatable');
    Route::resource('clients', 'ClientController');

    Route::apiResource('upload', 'DropzoneController'); //TODO: refactor by moving to API/ subfolder
    
    Route::get('stored-docs/{company:company_name}', 'StoredDocsController@show')->name('stored-docs.show');
    Route::get('fetch-doc/{client}', 'StoredDocsController@datatables')->name('stored-docs.resource');
});

resources/views/home.blade.php
@extends('layouts.app')

@push('laravel-style')
    <link href="{{ asset('css/laravel.css') }}" rel="stylesheet">
@endpush

@section('content')
<div class="container">
    <div class="content col-lg-5 mx-auto">
        
        @if (currentUser()->isAdmin())

            <div class="h1 my-5 links">
                <a href="{{ route('clients.index') }}">Your Clients</a>
            </div>
        
        @else
            <div class="h1 my-5 links">
                <a href="{{ route('upload.index') }}">Upload Documents</a> {{-- TODO: use policy --}}
            </div>
    
            <div class="h1 my-5 links" >
                <a href="{{ route('uploads.index') }}">Uploaded Documents</a>
            </div>
            
            <div class="h1 my-5 links">
                <a href="{{ route('stored-docs.show', getCurrentUserCompany()) }}">Filled Documents</a>
            </div>
        @endif
        
       
    </div>
</div>
    
{{-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div> --}}
@endsection