routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', function () {return view('welcome');});

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function(){
    
    Route::get('file/view/{file}', 'FileUploadController@serveFile')->name('serve-file');
    Route::get('file/download/{file}', 'FileUploadController@downloadFile')->name('download-file');
    Route::resource('uploads', 'FileUploadController');

    // Route::resource('clients.documents', 'ClientDocumentController')->shallow();
    Route::get('/test','ClientDocumentController@getType');
    Route::resource('clients.documents', 'ClientDocumentController')->scoped();

    Route::get('datatable/{clientId}', 'ClientController@datatables')->name('clients.datatable');
    Route::resource('clients', 'ClientController');

    Route::apiResource('upload', 'DropzoneController'); //TODO: refactor by moving to API/ subfolder
    
    Route::get('stored-docs/{company:company_name}', 'StoredDocsController@show')->name('stored-docs.show');
    Route::get('fetch-doc/{client}', 'StoredDocsController@datatables')->name('stored-docs.resource');
});

app/Http/Controllers/DropzoneController.php
<?php

namespace App\Http\Controllers;

use App\FileUpload;
use Illuminate\Http\Request;

class DropzoneController extends Controller
{
    public function index()
    {
        return view('dropzone.index');
    }

    public function store(Request $request)
    {
        $image = $request->file('file');
        $imageName = time().'-'.$image->getClientOriginalName();
        $path = $image->storeAs('documents',$imageName);  // a separete directories could be made for diff file types
        

        FileUpload::create([
            'path' => $path,
            'extension' => $image->extension(),
            'company_id' => currentUser()->getCompanyInfo->id,
        ]);
        
        return response()->json(['success' => $imageName]);
    }
}

resources/views/dropzone/index.blade.php
@extends('layouts.app')

@push('dropzone.css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/dropzone.min.css"/>
@endpush


@section('content')
    <div class="content">
        <div class="row">
            <div class="col">
                <form action="{{ route('upload.store') }}"
                class="dropzone"
                method="post"
                enctype="multipart/form-data"
                id="uploadImage"
                >
                @csrf
                </form>
            </div>
        </div>
    </div>

    
    @push('dropzone-scripts')
        <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/min/dropzone.min.js"></script>
        <script>
            Dropzone.options.uploadImage = {
                maxFilesize : 1,
            }
        </script>
    @endpush

@endsection