routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', function () {return view('welcome');});

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function(){
    
    Route::get('file/view/{file}', 'FileUploadController@serveFile')->name('serve-file');
    Route::get('file/download/{file}', 'FileUploadController@downloadFile')->name('download-file');
    Route::resource('uploads', 'FileUploadController');

    // Route::resource('clients.documents', 'ClientDocumentController')->shallow();
    Route::get('/test','ClientDocumentController@getType');
    Route::resource('clients.documents', 'ClientDocumentController')->scoped();

    Route::get('datatable/{clientId}', 'ClientController@datatables')->name('clients.datatable');
    Route::resource('clients', 'ClientController');

    Route::apiResource('upload', 'DropzoneController'); //TODO: refactor by moving to API/ subfolder
    
    Route::get('stored-docs/{company:company_name}', 'StoredDocsController@show')->name('stored-docs.show');
    Route::get('fetch-doc/{client}', 'StoredDocsController@datatables')->name('stored-docs.resource');
});

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;


use App\CompanyInfos;
use Illuminate\Support\Str;     
use App\Http\Requests\StoreClient;
use App\Mail\RegistrationCredentials;
use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Yajra\DataTables\DataTables;

class ClientController extends Controller
{

    public function __construct()
    {
        // $this->middleware('admin')->except(['show']);
        $this->authorizeResource(CompanyInfos::class, 'client');
    }
   
    public function index()
    {
        $clients = CompanyInfos::where('accountant_id',currentUser()->id)->get();
    
        if (request()->ajax()) {
            return DataTables::of($clients)
                    ->addColumn('action', function($data){
                        return view('clients.partial.view', compact('data'));
                        // $button = '<button type="button"
                        //             name="edit" id="'.$data->id.'"
                        //             class="edit btn btn-primary 
                        //             btn-sm">Edit</button>';
                        // $button .= '
                        //     &nbsp;&nbsp;&nbsp;<button
                        //     type="button" name="edit" id="'.$data->id.'"
                        //     class ="delete btn btn-danger btn-sm">Delete</button';
                        //     return $button;
                    })
                    ->addColumn('unfilled', function($client){
                        return $client->uploads()->where('accounted_for',0)->count();
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
       
        return view('clients.index', compact('clients'));
    }

    public function show(CompanyInfos $client)
    {
        // $this->authorize('view',$client);
        $uploads = $client->uploads;
        // dd($uploads,$client);

        return view('clients.show',compact(['client','uploads']));
    }

    public function store(StoreClient $request)
    {
        $data = $request->validated();
        // dd($data);
        $password = Str::random(8);
        
        $mailable = $data;
        $mailable['password'] = $password;
       
        User::create([
            'name' => $data['companyName'],
            'email' => $data['email'],
            'password' => Hash::make($password),
            // 'accountant_id' => auth()->user()->id,
            'isClient' => true,
        ]);

        CompanyInfos::create([
            'company_name' => $data['companyName'],
            'owner' => $data['ownerName'],
            'bulstat' => $data['bulstat'],
            'accountant_id' => auth()->user()->id,
            'user_id' => User::where('email',$data['email'])->get()[0]->id
        ]);
            
        Mail::to($data['email'])->send(new RegistrationCredentials($mailable));

        return back()->with('message','Client Registered');
    }

    public function datatables(CompanyInfos $clientId)
    {   
        // dd($clientId);
        $clientUploads = $clientId->uploads();


        return DataTables::of($clientUploads)
        ->addColumn('created_at', function($model) {
            return $model->created_at->diffForHumans();
        })
        ->addColumn('action', function($upload){
            return view('admin.partials.show-file', compact('upload'));
        })
        ->addColumn('action2', function($upload){
            return view('admin.partials.download-file', compact('upload'));
        })
        ->rawColumns(['action'])
        ->rawColumns(['action2'])
        ->make(true);

    }

}

resources/views/clients/index.blade.php
@extends('layouts.app')

@push('datatables')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js" type="text/javascript" defer></script>

@endpush

@section('content')


    <div class="container">
        <div class="mb-3">
            @include('clients.register-client-modal')
        </div>

        <table id="clients-table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Company Name</th>
                <th>Bulstat</th>
                <th>Action</th>
                <th>Unfilled</th>
            </tr>
            </thead>
        </table>
    </div>


    <script src="{{ asset('js/datatables/users.js') }}"></script>


@endsection

resources/views/clients/register-client-modal.blade.php
 
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#registerModal" data-whatever="@getbootstrap">Register New Client</button>

<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New client</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <div class="modal-body">
            <form id="client-form" method="POST" action="{{ route('clients.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name-label" class="col-form-label">Name:</label>
                    <input type="text" name="name" class="form-control" id="name-label">
                </div>
                <div class="form-group">
                    <label for="company-label" class="col-form-label">Company name:</label>
                    <input type="text" name="companyName" class="form-control" id="company-label">
                </div>
                <div class="form-group">
                    <label for="owner-label" class="col-form-label">Owner's name:</label>
                    <input type="text" name="ownerName" class="form-control" id="owner-label">
                </div>
                <div class="form-group">
                    <label for="bulstat-label" class="col-form-label">Bulstat:</label>
                    <input type="text" name="bulstat" class="form-control" id="bulstat-label">
                </div>
                <div class="form-group">
                    <label for="email-label" class="col-form-label">Email:</label>
                    <input type="email" name="email" class="form-control" id="email-label">
                </div>
            </form>
        </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <input type="submit" form="client-form" class="btn btn-primary" value="Register">
            </div>
        </div>
    </div>
</div>

resources/views/clients/show.blade.php
@extends('layouts.app')

@push('datatables')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js" type="text/javascript" defer></script>

@endpush

@section('content')


<div class="container">

    @if (session('message'))
        <div class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif


    <h1>Client's details</h1>
    <div class="row">
        <div class="col-sm my-3">
            <p>Company Name: {{ $client->company_name }}</p>
        </div>
        <div class="col-sm my-3">
            Owner: {{ $client->owner }}
        </div>
        <div class="col-sm my-3">
            <p>Bulstat: {{ $client->bulstat }}</p>
        </div>
        <div class="col-sm my-3">
            <p>Email: {{ $client->getAccountInfo->email }}</p>
        </div>
    </div> 

    {{-- <a href="{{ route('documents.index') }}" role="button" type="button" class="btn btn-danger">See All Unaccounted Docs</a> --}}

    <div class="container">
        <table id="company_table">
            <thead>
            <tr>
                <th>File Type</th>
                <th>Uploaded On</th>
                <th>Accounted For</th>
                <th>View</th>
                <th>Download</th>
            </tr>
            </thead>
        </table>
    </div>

</div>




{{-- old (static) way of rendering information about docs --}}
{{-- <x-user-uploads :client=$client :uploads=$uploads></x-user-uploads> --}}


<input type="hidden" id="clientId" value="{{ $client->id }}">
<input type="hidden" id="isClient" value="{{ currentUser()->isClient }}">


<script src="{{ asset('js/datatables/users-docs.js') }}"></script>


@endsection